version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '0.0.0.0:8080:80'
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    depends_on:
      - node

  node:
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./soccer:/app/soccer
      - ./select-conf.txt:/app/select-conf.txt
      - ./soccer-conf.txt:/app/soccer-conf.txt
      - ./soccer-ranking-conf.txt:/app/soccer-ranking-conf.txt
      - ./band-conf:/app/band-conf
