name: Build

on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
    branches: "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install packages
        run: pnpm install

      - name: Build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/index.html
